select FIRST_NAME as WORKER_NAME from worker;
select UPPER(FIRST_NAME) from worker;
select distinct(DEPARTMENT) from worker;
select FIRST_NAME from worker where FIRST_NAME like '___';
select substring(FIRST_NAME,1,3) from worker;
select position('a' in 'Amitabh') as position from worker;
select rtrim(FIRST_NAME) from worker;
select ltrim(DEPARTMENT) from worker;
select distinct(length(DEPARTMENT)) from worker;
select replace(FIRST_NAME, 'a','A') from worker;
select concat(FIRST_NAME," ", LAST_NAME) as COMPLETE_NAME from worker;
select * from worker order by FIRST_NAME; 
select * from worker where FIRST_NAME='Vipul' or First_NAME='Satish';
select * from worker where FIRST_NAME!='Vipul' and FIRST_NAME!='Satish';
select * from worker where DEPARTMENT='Admin';
select *from worker where FIRST_NAME like '%a%';
select *from worker where FIRST_NAME like '%a';
select * from worker where FIRST_NAME like '_____h';
select * from worker where SALARY between 100000 and 500000;
select * from worker where JOINING_DATE like '2014-02%';
select count(DEPARTMENT) from worker where DEPARTMENT='Admin';
select FIRST_NAME,LAST_NAME from worker where SALARY between 100000 and 500000;
select count(WORKER_ID),DEPARTMENT from worker GROUP BY DEPARTMENT order by DEPARTMENT desc;
select * from worker w,title t where w.WORKER_ID=t.WORKER_REF_ID and t.TITLE='Manager';
select * from title t,(select count(WORKER_REF_ID),TITLE FROM title group by TITLE HAVING COUNT(WORKER_REF_ID)=1) W WHERE t.TITLE=W.TITLE;
select * from worker where mod(WORKER_ID,2)!=0;
select * from worker where mod(WORKER_ID,2)=0;
create table WORKER_CLONE select * from WORKER;
select * from WORKER_CLONE;
select * from WORKER join BONUS on WORKER.WORKER_ID=BONUS.WORKER_REF_ID;
select * from WORKER where WORKER_ID not in(select WORKER_REF_ID from BONUS);
